In [1]:
import pandas as pd
from konlpy.tag import Okt
from collections import Counter
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc
import wordcloud
import re

df=pd.read_csv('./쓰레기배출량-유동인구.csv',encoding='utf-8')
df1=pd.read_csv('./유흥인구-쓰레기배출순위.csv',encoding='utf-8')

In [2]:
df

,Unnamed: 0,자치구1,순위1,배출량(C),처리방법.3,순위2,자치구,대중교통1일이용객수,구별인구수
0,26,강동구,4.0,555.5,4356.1,21,서초구,388991,435107.0
1,23,서초구,3.0,801.7,3566.8,22,강남구,388965,550209.0
2,24,강남구,3.0,718.0,3059.5,20,관악구,362357,517334.0
3,17,강서구,2.0,949.5,2213.8,1,중구,327000,136488.0
4,20,영등포구,2.0,556.1,2377.5,23,송파구,321916,682741.0
5,25,송파구,2.0,353.1,2041.2,13,마포구,320325,385925.0
6,13,은평구,2.0,311.2,2146.4,18,영등포구,286963,400986.0
7,5,성동구,2.0,181.2,1442.1,0,종로구,283986,161869.0
8,15,마포구,1.0,979.4,753.4,16,구로구,241704,439371.0
9,19,금천구,1.0,936.9,1798.5,7,성북구,234382,454744.0
10,22,관악구,1.0,666.5,1533.2,19,동작구,232535,408912.0
11,14,서대문구,1.0,604.9,1490.7,15,강서구,229160,598273.0
12,12,노원구,1.0,591.5,1366.8,4,광진구,212473,366972.0
13,8,중랑구,1.0,585.9,1461.3,10,노원구,211668,537303.0
14,21,동작구,1.0,514.3,1410.9,11,은평구,209803,484546.0
15,3,중구,1.0,468.2,1268.0,5,동대문구,203618,363023.0
16,6,광진구,1.0,379.4,1290.4,12,서대문구,191508,323171.0
17,7,동대문구,1.0,367.2,1234.7,8,강북구,183954,317695.0
18,9,성북구,1.0,354.6,1247.6,2,용산구,183323,245185.0
19,18,구로구,1.0,333.4,1111.4,3,성동구,165601,308979.0
20,4,용산구,1.0,140.8,1009.6,24,강동구,158597,440390.0
21,16,양천구,1.0,107.7923.9,14.0,양천구,152315,462285,NaN
22,2,종로구,882.0,735.3,6.0,중랑구,144365,402024,NaN
23,10,강북구,851.0,772.1,9.0,도봉구,134398,335631,NaN
24,11,도봉구,805.8,624.4,17.0,금천구,107472,251820,NaN

In [7]:
df=df.drop(columns=['Unnamed: 0','순위1','순위2','배출량(C)','구별인구수'], axis=1)

In [10]:
df['자치구']

0        서초구
1        강남구
2        관악구
3         중구
4        송파구
5        마포구
6       영등포구
7        종로구
8        구로구
9        성북구
10       동작구
11       강서구
12       광진구
13       노원구
14       은평구
15      동대문구
16      서대문구
17       강북구
18       용산구
19       성동구
20       강동구
21    152315
22    144365
23    134398
24    107472
Name: 자치구, dtype: object

In [3]:
df.groupby('자치구').sum()

        Unnamed: 0    순위1  처리방법.3  대중교통1일이용객수     구별인구수
자치구
107472          11  805.8    17.0      251820       0.0
134398          10  851.0     9.0      335631       0.0
144365           2  882.0     6.0      402024       0.0
152315          16    1.0    14.0      462285       0.0
강남구             23    3.0  3566.8      388965  550209.0
강동구              4    1.0  1009.6      158597  440390.0
강북구              7    1.0  1234.7      183954  317695.0
강서구             14    1.0  1490.7      229160  598273.0
관악구             24    3.0  3059.5      362357  517334.0
광진구             12    1.0  1366.8      212473  366972.0
구로구             15    1.0   753.4      241704  439371.0
노원구              8    1.0  1461.3      211668  537303.0
동대문구             3    1.0  1268.0      203618  363023.0
동작구             22    1.0  1533.2      232535  408912.0
마포구             25    2.0  2041.2      320325  385925.0
서대문구             6    1.0  1290.4      191508  323171.0
서초구             26    4.0  4356.1      388991  435107.0
성동구             18    1.0  1111.4      165601  308979.0
성북구             19    1.0  1798.5      234382  454744.0
송파구             20    2.0  2377.5      321916  682741.0
영등포구            13    2.0  2146.4      286963  400986.0
용산구              9    1.0  1247.6      183323  245185.0
은평구             21    1.0  1410.9      209803  484546.0
종로구              5    2.0  1442.1      283986  161869.0
중구              17    2.0  2213.8      327000  136488.0

In [12]:
df.to_csv('쓰레기배출량-유동인구(수정).csv')

In [13]:
df1

    Unnamed: 0  Unnamed: 0.1   자치구   배출량(C)  처리방법.3 signgu_nm  cnsmr_popltn_co
0            0            26   강동구   4555.5  4356.1       서초구      1431.168246
1            1            23   서초구  3,801.7  3566.8       강남구      1303.786779
2            2            24   강남구  3,718.0  3059.5       관악구       921.642378
3            3            17   강서구  2,949.5  2213.8       종로구       839.219076
4            4            20  영등포구  2,556.1  2377.5       강서구       734.316692
5            5            25   송파구  2,353.1  2041.2       송파구       636.907335
6            6            13   은평구  2,311.2  2146.4      영등포구       621.921280
7            7             5   성동구  2,181.2  1442.1       강북구       532.004950
8            8            15   마포구  1,979.4  1753.4       강동구       509.525868
9            9            19   금천구  1,936.9  1798.5       은평구       269.748989
10          10            22   관악구  1,666.5  1533.2       노원구       247.269906
11          11            14  서대문구  1,604.9  1490.7       성동구       239.776879
12          12            12   노원구  1,591.5  1366.8       마포구       224.790824
13          13             8   중랑구  1,585.9  1461.3       용산구       194.818714
14          14            21   동작구  1,514.3  1410.9       광진구       149.860549
15          15             3    중구  1,468.2  1268.0      동대문구        97.409357
16          16             6   광진구  1,379.4  1290.4      서대문구        89.916330
17          17             7  동대문구  1,367.2  1234.7        중구        89.916330
18          18             9   성북구  1,354.6  1247.6       구로구        67.437247
19          19            18   구로구  1,333.4  1111.4       중랑구        67.437247
20          20             4   용산구  1,140.8  1009.6       동작구        52.451192
21          21            16   양천구  1,107.7   923.9       성북구        44.958165
22          22             2   종로구      882   735.3       금천구        44.958165
23          23            10   강북구      851   772.1       도봉구        22.479082
24          24            11   도봉구    805.8   624.4       NaN              NaN

In [14]:
df1=df1.drop(columns=['Unnamed: 0','Unnamed: 0.1','배출량(C)'], axis=1)

In [15]:
df1

     자치구  처리방법.3 signgu_nm  cnsmr_popltn_co
0    강동구  4356.1       서초구      1431.168246
1    서초구  3566.8       강남구      1303.786779
2    강남구  3059.5       관악구       921.642378
3    강서구  2213.8       종로구       839.219076
4   영등포구  2377.5       강서구       734.316692
5    송파구  2041.2       송파구       636.907335
6    은평구  2146.4      영등포구       621.921280
7    성동구  1442.1       강북구       532.004950
8    마포구  1753.4       강동구       509.525868
9    금천구  1798.5       은평구       269.748989
10   관악구  1533.2       노원구       247.269906
11  서대문구  1490.7       성동구       239.776879
12   노원구  1366.8       마포구       224.790824
13   중랑구  1461.3       용산구       194.818714
14   동작구  1410.9       광진구       149.860549
15    중구  1268.0      동대문구        97.409357
16   광진구  1290.4      서대문구        89.916330
17  동대문구  1234.7        중구        89.916330
18   성북구  1247.6       구로구        67.437247
19   구로구  1111.4       중랑구        67.437247
20   용산구  1009.6       동작구        52.451192
21   양천구   923.9       성북구        44.958165
22   종로구   735.3       금천구        44.958165
23   강북구   772.1       도봉구        22.479082
24   도봉구   624.4       NaN              NaN

In [16]:
df1.to_csv('쓰레기배출량-유흥인구(수정).csv')

In [29]:
df3=pd.read_excel('./서울특별시 가로쓰레기통 설치정보(2019.9).xlsx')

In [30]:
df3

     2020년 가로쓰레기통(고정식) 설치 현황 (19.9. 기준) Unnamed: 1 Unnamed: 2     Unnamed: 3
0                                   NaN        NaN        NaN            NaN
1                                    연번       자치구명    도로(가로)명           설치위치
2                                     1        종로구        사직로      경복궁역 4번출구
3                                     2        종로구       자하문로        자하문로 12
4                                     3        종로구       자하문로        자하문로 44
...                                 ...        ...        ...            ...
6532                                432        강동구       아리수로    426 공영차고지 앞
6533                                433        강동구       아리수로  419 리슈빌오피스텔 앞
6534                                434        강동구       강동대로      207 윤선생 앞
6535                                435        강동구       천호대로           1092
6536                                436        강동구       천호대로    1027 신한은행 앞

[6537 rows x 4 columns]

In [34]:
df3=df3.groupby('Unnamed: 1').count()

In [35]:
df3

            2020년 가로쓰레기통(고정식) 설치 현황 (19.9. 기준)  Unnamed: 2  Unnamed: 3
Unnamed: 1
강남구                                        960         960         960
강동구                                        436         436         436
강북구                                        215         215         215
강서구                                        274         274         274
관악구                                        175         175         175
광진구                                        206         206         206
구로구                                        325         325         325
금천구                                        139         139         139
노원구                                         54          54          54
도봉구                                        235         235         235
동대문구                                       172         172         172
동작구                                        181         181         181
마포구                                        274         274         274
서대문구                                       290         290         290
서초구                                        250         250         250
성동구                                        172         172         172
성북구                                        175         175         175
송파구                                        301         301         301
양천구                                        216         216         216
영등포구                                       183         153         183
용산구                                        267         267         267
은평구                                        295         295         295
자치구명                                         1           1           1
종로구                                        304         304         304
중구                                         360         360         360
중랑구                                         76          76          76

In [36]:
df3=df3.drop(columns=['Unnamed: 3','Unnamed: 2'], axis=1)

In [37]:
df3

            2020년 가로쓰레기통(고정식) 설치 현황 (19.9. 기준)
Unnamed: 1
강남구                                        960
강동구                                        436
강북구                                        215
강서구                                        274
관악구                                        175
광진구                                        206
구로구                                        325
금천구                                        139
노원구                                         54
도봉구                                        235
동대문구                                       172
동작구                                        181
마포구                                        274
서대문구                                       290
서초구                                        250
성동구                                        172
성북구                                        175
송파구                                        301
양천구                                        216
영등포구                                       183
용산구                                        267
은평구                                        295
자치구명                                         1
종로구                                        304
중구                                         360
중랑구                                         76

In [38]:
df3.to_csv('2019년 가로휴지통갯수.csv')

In [45]:
df4=pd.read_csv('./2019년 가로휴지통갯수.csv',encoding="utf-8")
df5=pd.read_csv('./서울시자치구_유흥인구.csv')

In [44]:
df4

   Unnamed: 1  2020년 가로쓰레기통(고정식) 설치 현황 (19.9. 기준)
0         강남구                                 960
1         강동구                                 436
2         강북구                                 215
3         강서구                                 274
4         관악구                                 175
5         광진구                                 206
6         구로구                                 325
7         금천구                                 139
8         노원구                                  54
9         도봉구                                 235
10       동대문구                                 172
11        동작구                                 181
12        마포구                                 274
13       서대문구                                 290
14        서초구                                 250
15        성동구                                 172
16        성북구                                 175
17        송파구                                 301
18        양천구                                 216
19       영등포구                                 183
20        용산구                                 267
21        은평구                                 295
22        종로구                                 304
23         중구                                 360
24        중랑구                                  76

In [46]:
df5

   signgu_nm  cnsmr_popltn_co
0        서초구      1431.168246
1        강남구      1303.786779
2        관악구       921.642378
3        종로구       839.219076
4        강서구       734.316692
5        송파구       636.907335
6       영등포구       621.921280
7        강북구       532.004950
8        강동구       509.525868
9        은평구       269.748989
10       노원구       247.269906
11       성동구       239.776879
12       마포구       224.790824
13       용산구       194.818714
14       광진구       149.860549
15      동대문구        97.409357
16      서대문구        89.916330
17        중구        89.916330
18       구로구        67.437247
19       중랑구        67.437247
20       동작구        52.451192
21       성북구        44.958165
22       금천구        44.958165
23       도봉구        22.479082

In [54]:
df5.sort_index(ascending=False)

   signgu_nm  cnsmr_popltn_co
23       도봉구        22.479082
22       금천구        44.958165
21       성북구        44.958165
20       동작구        52.451192
19       중랑구        67.437247
18       구로구        67.437247
17        중구        89.916330
16      서대문구        89.916330
15      동대문구        97.409357
14       광진구       149.860549
13       용산구       194.818714
12       마포구       224.790824
11       성동구       239.776879
10       노원구       247.269906
9        은평구       269.748989
8        강동구       509.525868
7        강북구       532.004950
6       영등포구       621.921280
5        송파구       636.907335
4        강서구       734.316692
3        종로구       839.219076
2        관악구       921.642378
1        강남구      1303.786779
0        서초구      1431.168246

In [55]:
a=pd.concat([df4,df5],axis=1)

In [57]:
a.to_csv('휴지통-유흥인구.csv')

In [59]:
df6=pd.read_csv('./유동인구.csv',encoding='cp949')

In [60]:
df6

    Unnamed: 0   자치구  스타벅스매장수   사업체수    종사자수  대중교통1일이용객수   구별인구수
0            1   종로구       41  39679  260446      283986  161869
1            2    중구       56  60127  392568      327000  136488
2            3   용산구       21  20254  135240      183323  245185
3            4   성동구       10  28343  178243      165601  308979
4            5   광진구       16  24445  126305      212473  366972
5            6  동대문구        9  31324  138400      203618  363023
6            7   중랑구        8  28228  103345      144365  402024
7            8   성북구       14  23617  111005      234382  454744
8            9   강북구        6  19014   73904      183954  317695
9           10   도봉구        3  18628   72939      134398  335631
10          11   노원구       13  26618  116684      211668  537303
11          12   은평구        8  24681   93631      209803  484546
12          13  서대문구       20  20095  113819      191508  323171
13          14   마포구       32  37290  247276      320325  385925
14          15   양천구       17  25894  121582      152315  462285
15          16   강서구       20  39458  257494      229160  598273
16          17   구로구       11  38756  225668      241704  439371
17          18   금천구       11  33814  242686      107472  251820
18          19  영등포구       39  42370  373478      286963  400986
19          20   동작구       11  19793  106159      232535  408912
20          21   관악구       11  25505  115329      362357  517334
21          22   서초구       48  46940  438985      388991  435107
22          23   강남구       86  71027  698840      388965  550209
23          24   송파구       33  48644  341201      321916  682741
24          25   강동구       16  29080  141770      158597  440390

In [65]:
b=pd.concat([df4,df6],axis=1)

In [68]:
b.to_csv('유동-쓰레기함.csv')

In [70]:
d=pd.read_csv('./유동인구.csv',encoding='cp949')

In [71]:
d

    Unnamed: 0   자치구  스타벅스매장수   사업체수    종사자수  대중교통1일이용객수   구별인구수
0            1   종로구       41  39679  260446      283986  161869
1            2    중구       56  60127  392568      327000  136488
2            3   용산구       21  20254  135240      183323  245185
3            4   성동구       10  28343  178243      165601  308979
4            5   광진구       16  24445  126305      212473  366972
5            6  동대문구        9  31324  138400      203618  363023
6            7   중랑구        8  28228  103345      144365  402024
7            8   성북구       14  23617  111005      234382  454744
8            9   강북구        6  19014   73904      183954  317695
9           10   도봉구        3  18628   72939      134398  335631
10          11   노원구       13  26618  116684      211668  537303
11          12   은평구        8  24681   93631      209803  484546
12          13  서대문구       20  20095  113819      191508  323171
13          14   마포구       32  37290  247276      320325  385925
14          15   양천구       17  25894  121582      152315  462285
15          16   강서구       20  39458  257494      229160  598273
16          17   구로구       11  38756  225668      241704  439371
17          18   금천구       11  33814  242686      107472  251820
18          19  영등포구       39  42370  373478      286963  400986
19          20   동작구       11  19793  106159      232535  408912
20          21   관악구       11  25505  115329      362357  517334
21          22   서초구       48  46940  438985      388991  435107
22          23   강남구       86  71027  698840      388965  550209
23          24   송파구       33  48644  341201      321916  682741
24          25   강동구       16  29080  141770      158597  440390

In [77]:
d=d.drop(columns=['Unnamed: 0', '스타벅스매장수','사업체수','종사자수'], axis=1)

In [78]:
d

     자치구  대중교통1일이용객수   구별인구수
0    종로구      283986  161869
1     중구      327000  136488
2    용산구      183323  245185
3    성동구      165601  308979
4    광진구      212473  366972
5   동대문구      203618  363023
6    중랑구      144365  402024
7    성북구      234382  454744
8    강북구      183954  317695
9    도봉구      134398  335631
10   노원구      211668  537303
11   은평구      209803  484546
12  서대문구      191508  323171
13   마포구      320325  385925
14   양천구      152315  462285
15   강서구      229160  598273
16   구로구      241704  439371
17   금천구      107472  251820
18  영등포구      286963  400986
19   동작구      232535  408912
20   관악구      362357  517334
21   서초구      388991  435107
22   강남구      388965  550209
23   송파구      321916  682741
24   강동구      158597  440390

In [79]:
d1=pd.read_csv('./쓰레기배출량-유동인구(수정).csv', encoding='utf-8')

In [81]:
d1=d1.drop(columns=['Unnamed: 0', '자치구','대중교통1일이용객수'], axis=1)

In [82]:
d1

    자치구1  처리방법.3
0    강동구  4356.1
1    서초구  3566.8
2    강남구  3059.5
3    강서구  2213.8
4   영등포구  2377.5
5    송파구  2041.2
6    은평구  2146.4
7    성동구  1442.1
8    마포구   753.4
9    금천구  1798.5
10   관악구  1533.2
11  서대문구  1490.7
12   노원구  1366.8
13   중랑구  1461.3
14   동작구  1410.9
15    중구  1268.0
16   광진구  1290.4
17  동대문구  1234.7
18   성북구  1247.6
19   구로구  1111.4
20   용산구  1009.6
21   양천구    14.0
22   종로구     6.0
23   강북구     9.0
24   도봉구    17.0

In [83]:
pd.concat([d,d1],axis=1)

     자치구  대중교통1일이용객수   구별인구수  자치구1  처리방법.3
0    종로구      283986  161869   강동구  4356.1
1     중구      327000  136488   서초구  3566.8
2    용산구      183323  245185   강남구  3059.5
3    성동구      165601  308979   강서구  2213.8
4    광진구      212473  366972  영등포구  2377.5
5   동대문구      203618  363023   송파구  2041.2
6    중랑구      144365  402024   은평구  2146.4
7    성북구      234382  454744   성동구  1442.1
8    강북구      183954  317695   마포구   753.4
9    도봉구      134398  335631   금천구  1798.5
10   노원구      211668  537303   관악구  1533.2
11   은평구      209803  484546  서대문구  1490.7
12  서대문구      191508  323171   노원구  1366.8
13   마포구      320325  385925   중랑구  1461.3
14   양천구      152315  462285   동작구  1410.9
15   강서구      229160  598273    중구  1268.0
16   구로구      241704  439371   광진구  1290.4
17   금천구      107472  251820  동대문구  1234.7
18  영등포구      286963  400986   성북구  1247.6
19   동작구      232535  408912   구로구  1111.4
20   관악구      362357  517334   용산구  1009.6
21   서초구      388991  435107   양천구    14.0
22   강남구      388965  550209   종로구     6.0
23   송파구      321916  682741   강북구     9.0
24   강동구      158597  440390   도봉구    17.0

In [84]:
d.to_csv('유동인구(구별인구수).csv')
d1.to_csv('자치구,배출방법.3.csv')

In [86]:
d2=pd.read_csv('./도로구간별 추정 유동인구.csv',encoding='cp949')

In [87]:
d2

,기준_년월_코드(STDR_YM_CD),도로링크_ID(RD_LINK_ID),시군구코드(SIGNGU_CD),시군구명(SIGNGU_NM),행정동코드(ADSTRD_CD),행정동명(ADSTRD_NM),요일코드(DAYWEEK_CD),연령대코드(AGRDE_CD),시간대코드(TMZON_CD),유동인구_수(FLPOP_CO)
0,201612,132349,11290,종로구,11560515,등촌2동,2,20,5,8.593500
1,201612,82752,11545,강북구,11110600,화곡6동,2,50,5,1.015000
2,201612,97365,11305,구로구,11620765,성수1가1동,2,30,3,20.125778
3,201612,21049,11560,금천구,11260580,공릉1동,1,0,6,10.487500
4,201612,37768,11545,중랑구,11290555,오류2동,2,50,2,3.784667
...,...,...,...,...,...,...,...,...,...,...
495,201612,58675,11230,관악구,11215750,을지로동,2,60,1,40.273500
496,201612,14069,11290,성북구,11620625,이문1동,1,30,6,0.000000
497,201612,156001,11230,관악구,11410660,혜화동,2,30,0,3.640000
498,201612,112505,11230,광진구,11305606,수유3동,1,50,3,11.596000
499,201612,147787,11560,중랑구,11110700,삼성동,1,10,0,1.275000

In [92]:
d2=d2.groupby('시군구명(SIGNGU_NM)').sum()

In [93]:
d2

,기준_년월_코드(STDR_YM_CD),도로링크_ID(RD_LINK_ID),시군구코드(SIGNGU_CD),행정동코드(ADSTRD_CD),요일코드(DAYWEEK_CD),연령대코드(AGRDE_CD),시간대코드(TMZON_CD),유동인구_수(FLPOP_CO)
시군구명(SIGNGU_NM),,,,,,,,
강남구,4032240,1495024,228575,228077152,30,470,62,174.326408
강동구,1814508,770252,103335,102740522,12,400,21,0.370800
강북구,6451584,2427649,366080,364135108,44,950,96,550.641932
강서구,3427404,1511392,194450,193515732,24,580,60,521.790919
관악구,5040300,2163917,284650,284050025,36,790,68,470.553150
광진구,5241912,1830557,295505,297381049,40,1040,78,247.862162
구로구,4435464,2027075,249790,250433176,38,660,78,480.197223
금천구,2620956,922122,147310,147842550,17,300,39,49.882280
노원구,2822568,1446481,160235,159988775,16,280,48,85.581398
도봉구,1814508,771041,101715,103115685,14,350,27,60.563444
동대문구,5040300,1981182,286060,284755565,38,700,91,258.243670
동작구,3629016,1728561,204285,204775914,25,480,51,265.614869
마포구,5241912,2728940,297590,297381212,33,830,95,159.779974
서대문구,6249972,3176938,353185,354298989,51,780,78,357.122475
서초구,3427404,1769588,193775,193125654,27,500,45,189.396722
성동구,3427404,1026717,192965,193785874,24,420,48,138.550639
성북구,7056420,2579939,399470,398531284,52,1000,107,373.698759
송파구,4435464,1671224,250300,250133925,32,610,52,424.634077
양천구,2419344,821673,136320,136372625,15,430,35,127.155467
영등포구,4435464,2415899,250345,250613657,30,800,74,80.747050
용산구,3225792,1408932,182560,182839711,24,510,55,113.170308
은평구,2419344,1134567,136275,138397555,19,400,46,30.138896
종로구,5443524,2749574,307455,308072065,37,670,88,689.378656
중구,2822568,1491036,159815,158788845,22,600,36,45.491095
중랑구,3830628,1973243,215620,216126625,29,530,60,965.785944

In [95]:
d2=d2.drop(columns=['기준_년월_코드(STDR_YM_CD)', '도로링크_ID(RD_LINK_ID)','시군구코드(SIGNGU_CD)','행정동코드(ADSTRD_CD)','요일코드(DAYWEEK_CD)','연령대코드(AGRDE_CD)','시간대코드(TMZON_CD)'], axis=1)

KeyError: "['기준_년월_코드(STDR_YM_CD)' '도로링크_ID(RD_LINK_ID)' '시군구코드(SIGNGU_CD)'\n '행정동코드(ADSTRD_CD)' '요일코드(DAYWEEK_CD)' '연령대코드(AGRDE_CD)' '시간대코드(TMZON_CD)'] not found in axis"

In [97]:
d2.to_csv('도로구간별-유동인구.csv')

In [108]:
sobi=pd.read_csv('./서울시유흥소비인구.csv',encoding='utf-8')

In [113]:
sobi

,Unnamed: 0,gov_dn_cd,bntr_nm,signgu_nm,adstrd_nm,de,sex_se,year_se,cnsmr_popltn_co
0,0,1111053000,서울특별시,종로구,사직동,20200804,X,xx,29.972110
1,1,1111053000,서울특별시,종로구,사직동,20200807,M,50,22.479082
2,2,1111053000,서울특별시,종로구,사직동,20200807,X,xx,22.479082
3,3,1111053000,서울특별시,종로구,사직동,20200808,X,xx,22.479082
4,4,1111053000,서울특별시,종로구,사직동,20200811,M,60,22.479082
...,...,...,...,...,...,...,...,...,...
7085,7085,1174068500,서울특별시,강동구,길동,20201031,M,25,29.972110
7086,7086,1174068500,서울특별시,강동구,길동,20201031,M,40,37.465137
7087,7087,1174068500,서울특별시,강동구,길동,20201031,M,50,22.479082
7088,7088,1174068500,서울특별시,강동구,길동,20201031,M,60,22.479082
7089,7089,1174068500,서울특별시,강동구,길동,20201031,X,xx,67.437247

In [126]:

#sobi1=(sobi.signgu_nm=='서초구')

sobi1=sobi.loc[sobi['signgu_nm']=='서초구']

In [128]:
sobi1

,Unnamed: 0,gov_dn_cd,bntr_nm,signgu_nm,adstrd_nm,de,sex_se,year_se,cnsmr_popltn_co
4800,4800,1165051000,서울특별시,서초구,서초1동,20200804,X,xx,22.479082
4801,4801,1165051000,서울특별시,서초구,서초1동,20200806,M,25,22.479082
4802,4802,1165051000,서울특별시,서초구,서초1동,20200812,M,25,22.479082
4803,4803,1165051000,서울특별시,서초구,서초1동,20200812,X,xx,29.972110
4804,4804,1165051000,서울특별시,서초구,서초1동,20200815,M,30,29.972110
...,...,...,...,...,...,...,...,...,...
5190,5190,1165054000,서울특별시,서초구,잠원동,20201018,M,30,22.479082
5191,5191,1165054000,서울특별시,서초구,잠원동,20201020,X,xx,29.972110
5192,5192,1165054000,서울특별시,서초구,잠원동,20201025,M,20,29.972110
5193,5193,1165054000,서울특별시,서초구,잠원동,20201025,M,25,22.479082
5194,5194,1165054000,서울특별시,서초구,잠원동,20201025,X,xx,22.479082

In [130]:
sobi1=sobi1.drop(columns=['Unnamed: 0','gov_dn_cd','bntr_nm','signgu_nm','de','sex_se','year_se'], axis=1)

In [133]:
sobi1.groupby('adstrd_nm').sum()

           cnsmr_popltn_co
adstrd_nm
서초1동            284.735044
서초2동            247.269906
서초3동           1078.995955
서초4동          34325.558817
잠원동             352.172291

In [161]:
data=pd.read_csv('./INNER_PEOPLE_20211121.csv',encoding='cp949')

In [162]:
data

,"?""기준일ID""",시간대구분,행정동코드,거주지 자치구 코드,총생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세부터74세생활인구수,여자75세부터79세생활인구수,장기체류외국인수
0,20211121,0,11110515,11110,520,4.3747,31.0514,123.3358,18.4109,26.7933,...,19.9546,14.7837,14.6276,13.4345,17.0096,17.6885,12.2087,12.0247,8.9744,*
1,20211121,0,11110515,11140,32,*,*,10.3852,*,*,...,*,*,*,*,*,*,*,*,*,*
2,20211121,0,11110515,11170,23,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
3,20211121,0,11110515,11200,22,*,*,*,*,8.3493,...,*,*,*,*,*,*,*,*,4.1572,*
4,20211121,0,11110515,11215,7,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252000,20211121,23,11740700,11620,3,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
252001,20211121,23,11740700,11650,25,*,5.3556,*,*,*,...,*,*,*,*,*,*,*,*,5.4613,*
252002,20211121,23,11740700,11680,35,*,*,*,*,*,...,4.0042,*,*,*,*,*,*,4.2568,*,*
252003,20211121,23,11740700,11710,149,*,*,*,12.8634,10.7537,...,15.1565,*,*,5.8797,9.5316,8.8401,8.6554,4.2314,*,9.1413
252004,20211121,23,11740700,11740,2073,69.4234,57.0874,51.7249,82.3648,65.3897,...,97.3379,82.4106,93.6933,71.3404,113.0299,111.0191,76.1869,48.6705,35.4202,22.4513

In [159]:
data['거주지 자치구 코드']=data[(data['거주지 자치구 코드'] == '11110')] = '종로구'

In [157]:
data['거주지 자치구 코드'] = data['거주지 자치구 코드'].str.replace('11110','종로구')

AttributeError: Can only use .str accessor with string values!

In [163]:
data

,"?""기준일ID""",시간대구분,행정동코드,거주지 자치구 코드,총생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세부터74세생활인구수,여자75세부터79세생활인구수,장기체류외국인수
0,20211121,0,11110515,11110,520,4.3747,31.0514,123.3358,18.4109,26.7933,...,19.9546,14.7837,14.6276,13.4345,17.0096,17.6885,12.2087,12.0247,8.9744,*
1,20211121,0,11110515,11140,32,*,*,10.3852,*,*,...,*,*,*,*,*,*,*,*,*,*
2,20211121,0,11110515,11170,23,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
3,20211121,0,11110515,11200,22,*,*,*,*,8.3493,...,*,*,*,*,*,*,*,*,4.1572,*
4,20211121,0,11110515,11215,7,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252000,20211121,23,11740700,11620,3,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
252001,20211121,23,11740700,11650,25,*,5.3556,*,*,*,...,*,*,*,*,*,*,*,*,5.4613,*
252002,20211121,23,11740700,11680,35,*,*,*,*,*,...,4.0042,*,*,*,*,*,*,4.2568,*,*
252003,20211121,23,11740700,11710,149,*,*,*,12.8634,10.7537,...,15.1565,*,*,5.8797,9.5316,8.8401,8.6554,4.2314,*,9.1413
252004,20211121,23,11740700,11740,2073,69.4234,57.0874,51.7249,82.3648,65.3897,...,97.3379,82.4106,93.6933,71.3404,113.0299,111.0191,76.1869,48.6705,35.4202,22.4513

In [166]:
data=data.groupby('거주지 자치구 코드').sum()

In [167]:
data

                ?"기준일ID"   시간대구분         행정동코드   총생활인구수
거주지 자치구 코드
11110       203768521922  115728  115257012915  1175279
11140       203202610534  115322  114930840006  1209268
11170       203222821655  115310  114952859056  1560256
11200       204051477616  116073  115423152529  1991085
11215       203788733043  115896  115280260131  2417032
11230       205001400303  116569  115965437691  2334174
11260       203040921566  115439  114847068184  2411483
11290       205062033666  116541  115995694960  3027549
11305       201929309911  114969  114205611594  3395324
11320       200352842473  113922  113311615603  1986122
11350       203788733043  116027  115270702103  3157236
11380       204496122278  116386  115674005836  2721034
11410       203970633132  116215  115382008727  2453895
11440       205304567118  116691  116137812589  2566502
11470       200797487135  114147  113596993086  2242017
11500       205264144876  116691  116115800770  3190078
11530       203606832954  115597  115183638393  2388789
11545       196553151725  111917  111228962338  1349217
11560       204920555819  116407  115926305716  2783119
11590       204779077972  116417  115844302772  2423951
11620       205284355997  116695  116127752463  3167615
11650       204940766940  116584  115937400361  2488007
11680       205607733933  116978  116309781700  3186575
11710       205587522812  116938  116299061100  3884396
11740       204981189182  116505  115955391770  3799327

In [169]:
data=data.drop(columns=['?"기준일ID"','시간대구분','행정동코드'])

In [170]:
data

             총생활인구수
거주지 자치구 코드
11110       1175279
11140       1209268
11170       1560256
11200       1991085
11215       2417032
11230       2334174
11260       2411483
11290       3027549
11305       3395324
11320       1986122
11350       3157236
11380       2721034
11410       2453895
11440       2566502
11470       2242017
11500       3190078
11530       2388789
11545       1349217
11560       2783119
11590       2423951
11620       3167615
11650       2488007
11680       3186575
11710       3884396
11740       3799327

In [171]:
data['거주지 자치구 코드']=data[(data['거주지 자치구 코드'] == '11110')] = '종로구'

In [174]:
data=data.drop(columns=['거주지 자치구 코드'])

In [175]:
data.to_csv('2021서울생활인구.csv')

In [176]:
data1=pd.read_excel('./배달.xls')

In [178]:
data1.to_csv('배달.csv')

In [179]:
data2=pd.read_excel('./주거지역.xls')

In [187]:
data2

,기간,자치구,구분,구분.1,구분.2,구분.3,구분.4,구분.5,구분.6,구분.7,...,구분.12,구분.13,구분.14,구분.15,구분.16,구분.17,구분.18,구분.19,구분.20,구분.21
0,기간,자치구,용도지역총합계,주거지역,주거지역,주거지역,주거지역,주거지역,주거지역,주거지역,...,상업지역,상업지역,상업지역,상업지역,공업지역,공업지역,녹지지역,녹지지역,녹지지역,녹지지역
1,기간,자치구,용도지역총합계,소계,전용주거지역,전용주거지역,전용주거지역,일반주거지역,일반주거지역,일반주거지역,...,중심,일반,근린,유통,소계,준공업,소계,보전,생산,자연
2,기간,자치구,용도지역총합계,소계,전용주거지역 계,제1종전용,제2종전용,일반주거지역 계,제1종일반,제2종일반(7층이하),...,중심,일반,근린,유통,소계,준공업,소계,보전,생산,자연
3,2020,서울특별시,605598290,326043340,5759953,5007957,751996,306908218,67403028,86073913,...,358676,22873609,827881,1539108,19974140,19974140,233981536,72603,1057622,232851311
4,2020,종로구,23972507,9830838,1589410,1589410,-,8042329,4376462,2198489,...,-,2937285,-,-,-,-,11204384,-,-,11204384
5,2020,중구,9974292,6037439,-,-,-,5764992,2767697,1276251,...,321414,3590304,-,-,-,-,25135,-,-,25135
6,2020,용산구,21898766,12107810,224153,224153,-,11323928,4145163,3285406,...,-,1260795,-,-,-,-,8530162,72603,-,8457559
7,2020,성동구,16804426,9947641,-,-,-,9683269,2386869,3112282,...,-,397688,3052,72405,2051234,2051234,4332406,-,-,4332406
8,2020,광진구,17075115,11596961,140987,140987,-,10472838,2239038,2895373,...,-,203281,-,-,-,-,5274873,-,-,5274873
9,2020,동대문구,14245433,13034193,-,-,-,12466788,2702669,3534257,...,-,745441,62456,20262,-,-,383081,-,-,383081
10,2020,중랑구,18531520,10821891,-,-,-,9977441,1044310,4250594,...,-,255092,102350,-,-,-,7352187,-,-,7352187
11,2020,성북구,24621432,17829610,990658,990658,-,16281182,5170298,4567776,...,-,332833,64396,-,-,-,6394593,-,-,6394593
12,2020,강북구,23636019,10979002,-,-,-,10546177,2921021,4241367,...,-,272237,-,-,-,-,12384780,-,-,12384780
13,2020,도봉구,20679052,8089653,-,-,-,7666000,1773756,2630032,...,-,239431,19228,-,1489295,1489295,10841445,-,-,10841445
14,2020,노원구,35595942,13978881,92455,13361,79094,13518019,1355487,2611717,...,-,590480,-,-,-,-,21026581,-,-,21026581
15,2020,은평구,29788522,15365100,796387,123485,672902,13551373,3065767,4420432,...,-,422289,99053,-,-,-,13902080,-,-,13902080
16,2020,서대문구,17685973,15439372,354625,354625,-,14739290,6589067,2394134,...,-,274391,9155,-,-,-,1963055,-,-,1963055
17,2020,마포구,23890251,13391126,-,-,-,12565203,1003364,4796122,...,37262,757236,89128,56562,-,-,9558937,-,-,9558937
18,2020,양천구,17469613,12536636,-,-,-,12201316,1336705,3622034,...,-,733026,63804,-,92872,92872,4043275,-,-,4043275
19,2020,강서구,41462488,14717824,157968,157968,-,13746512,2425477,4785380,...,-,992742,82791,248255,2919995,2919995,22500881,-,371340,22129541
20,2020,구로구,20136328,10269448,-,-,-,9976892,1276259,3966323,...,-,513589,-,-,4195729,4195729,5157562,-,857,5156705
21,2020,금천구,13012685,5845488,-,-,-,5571845,1407087,2451981,...,-,102906,46716,-,4121945,4121945,2895630,-,-,2895630
22,2020,영등포구,24354829,8013839,-,-,-,7067386,526257,3116032,...,-,2559127,48133,-,5024926,5024926,8708804,-,-,8708804
23,2020,동작구,16387882,13792930,-,-,-,13538949,4022213,3743236,...,-,267548,30777,46298,-,-,2250329,-,-,2250329
24,2020,관악구,29563482,15325411,-,-,-,14630054,5308646,4944960,...,-,392024,-,-,-,-,13846047,-,-,13846047
25,2020,서초구,46899887,18885147,680243,680243,-,17837801,3394881,3036881,...,-,1322182,-,-,-,-,26692558,-,-,26692558
26,2020,강남구,39497268,24228249,614211,614211,-,23303938,3482402,3458169,...,-,1946139,-,-,-,-,13322880,-,263088,13059792
27,2020,송파구,33858375,21013419,72137,72137,-,20060439,1891004,4591705,...,-,1182622,9067,1095326,-,-,10557941,-,422337,10135604
28,2020,강동구,24556203,12965432,46719,46719,-,12374257,791130,2142980,...,-,582922,97775,-,78144,78144,10831930,-,-,10831930

In [202]:
data2=data2.drop(columns=['기간','구분','구분.1','구분.2','구분.3','구분.4',
                   '구분.6','구분.7','구분.8','구분.9','구분.10',
                   '구분.11','구분.12','구분.13','구분.14','구분.15',
                   '구분.16','구분.17','구분.18','구분.19',
                   '구분.20','구분.21',],axis=1)

In [204]:
data2.to_csv('주거지역.csv')

In [207]:
data3=pd.read_excel('./교통수단.xls')
data3

,기간,대분류,분류,도보,자전거,자전거+기타교통수단,오토바이,버스,지하철(철도),버스+지하철,택시,승용차,승용차+버스,승용차+지하철,기타
0,2020,서울시,서울시,18.2,2.5,0.3,0.9,23.3,14.3,21.2,0.1,16.5,0.9,1.5,0.3
1,2020,성별,남자,14.0,2.8,0.4,1.3,19.7,14.6,20.7,0.1,23.1,1.0,1.9,0.3
2,2020,성별,여자,23.7,2.0,0.3,0.2,28.1,13.8,21.7,0.1,8.0,0.7,1.1,0.3
3,2020,연령별,10대,48.3,4.9,0.8,-,34.6,2.0,8.8,-,0.3,0.0,0.2,-
4,2020,연령별,20대,13.6,1.5,0.3,0.7,26.1,18.1,34.2,0.1,3.8,0.5,0.7,0.4
5,2020,연령별,30대,9.9,2.9,0.3,0.5,20.6,19.5,24.9,0.2,17.7,1.0,2.1,0.3
6,2020,연령별,40대,12.7,2.5,0.4,0.5,18.3,17.0,20.1,0.2,23.8,1.6,2.3,0.5
7,2020,연령별,50대,17.3,2.0,0.3,1,20.4,11.8,16.8,0.2,26.8,1.1,2.2,0.2
8,2020,연령별,60대 이상,29.5,2.7,0.1,2.2,27.9,7.3,10.9,0.1,18.2,0.5,0.6,0.1
9,2020,학력별,중졸 이하,50.7,2.8,0.3,2.6,24.6,4.2,8.2,0.2,5.9,0.1,0.2,0.1
10,2020,학력별,고졸 이하,27.7,3.2,0.2,1.5,30.0,8.4,13.6,0.1,14.0,0.5,0.7,0.2
11,2020,학력별,대졸 이하,10.8,2.1,0.3,0.4,21.2,17.7,26.2,0.1,17.9,1.0,1.8,0.4
12,2020,학력별,대학원 이상,12.8,2.2,1,0.2,10.1,18.8,20.9,0.3,26.4,2.7,4.0,0.7
13,2020,소득별,100 만원 미만,30.6,3.7,0.7,1.4,25.8,19.0,17.0,0.1,0.2,0.3,0.7,0.5
14,2020,소득별,100-200만 미만,29.6,1.9,0.3,1.5,27.1,12.8,20.2,0.5,4.2,0.7,0.8,0.4
15,2020,소득별,200-300만 미만,21.0,3.5,0.4,1.2,27.4,12.7,20.0,0.2,10.5,1.4,1.4,0.3
16,2020,소득별,300-400만 미만,18.5,2.8,0.4,0.8,23.8,14.9,19.8,0.2,16.5,1.1,1.1,0.2
17,2020,소득별,400-500만 미만,18.5,2.8,0.4,1,24.3,13.8,20.7,0,16.7,0.5,1.0,0.4
18,2020,소득별,500만 이상,15.2,2.0,0.3,0.6,21.2,14.6,22.4,0.1,20.4,0.9,1.9,0.3
19,2020,혼인상태별,기혼,15.7,2.6,0.3,1,19.7,14.6,18.1,0.2,24.2,1.2,2.2,0.3
20,2020,혼인상태별,미혼,19.3,2.5,0.5,0.3,26.2,15.5,27.2,0.1,6.6,0.6,0.7,0.4
21,2020,혼인상태별,이혼/사별/기타,29.4,1.7,0.2,2.1,34.1,6.0,12.7,0.1,12.7,0.3,0.6,0.1
22,2020,지역대분류,도심권,24.5,2.3,0.4,1.5,24.9,10.6,17.7,0.1,15.6,0.9,1.4,0.2
23,2020,지역대분류,동북권,17.9,2.7,0.4,0.8,24.4,14.6,20.5,0.1,15.9,0.8,1.7,0.2
24,2020,지역대분류,서북권,16.4,2.5,0.2,0.9,28.0,12.9,22.8,0.2,13.6,0.8,1.4,0.2
25,2020,지역대분류,서남권,18.3,2.1,0.5,0.9,22.4,14.1,23.5,0.1,15.7,0.9,1.2,0.4
26,2020,지역대분류,동남권,17.9,2.7,0.1,0.7,19.8,15.7,18.5,0.3,20.9,1.2,1.9,0.3
27,2020,종로구,종로구,21.3,3.1,0.2,1.4,27.9,9.7,17.9,0.2,16.3,1.6,0.4,-
28,2020,중구,중구,23.4,1.7,0.5,0.9,22.5,14.9,21.6,-,11.1,0.4,2.5,0.5
29,2020,용산구,용산구,27.2,2.1,0.5,2,24.3,8.7,15.3,0,17.7,0.7,1.3,0.2
30,2020,성동구,성동구,19.7,2.6,1.3,0.2,17.0,18.2,22.5,0,15.8,0.5,2.0,0.3
31,2020,광진구,광진구,24.0,2.9,-,0.5,21.6,18.0,19.6,0.1,11.0,0.9,1.0,0.3
32,2020,동대문구,동대문구,15.7,2.3,0.5,1.7,24.6,14.3,19.7,0.1,18.9,1.2,1.2,-
33,2020,중랑구,중랑구,14.2,2.8,0.6,0.5,26.6,15.3,19.2,-,18.3,0.8,1.5,0.1
34,2020,성북구,성북구,16.4,2.6,0.2,2.1,24.1,13.6,23.7,0.4,14.2,0.9,1.3,0.5
35,2020,강북구,강북구,17.6,2.0,0.1,0.8,24.5,11.6,20.5,0,20.5,0.6,1.7,0
36,2020,도봉구,도봉구,23.3,3.0,0.1,0.1,23.0,14.2,19.0,-,14.0,0.7,2.2,0.4
37,2020,노원구,노원구,15.4,3.1,0.4,0.3,29.9,12.8,20.0,-,15.2,0.5,2.2,0.2
38,2020,은평구,은평구,13.4,2.2,0.3,0,30.6,13.4,27.0,0.3,10.4,0.5,1.7,0.1
39,2020,서대문구,서대문구,14.9,2.6,0.1,1,26.5,12.8,23.4,0.3,15.5,1.0,1.5,0.4
40,2020,마포구,마포구,21.2,2.6,0.2,1.9,26.1,12.3,17.3,0.1,16.0,0.9,1.1,0.3
41,2020,양천구,양천구,17.9,2.7,0.4,0.1,21.1,8.8,26.3,0.1,20.1,0.9,1.2,0.4
42,2020,강서구,강서구,20.6,1.4,0.6,1.4,20.0,12.4,24.1,0.1,16.8,0.8,1.6,0.2
43,2020,구로구,구로구,20.4,2.2,0.5,0.8,21.1,15.0,20.6,-,17.6,0.6,1.1,0.1
44,2020,금천구,금천구,27.0,2.7,0.3,0.8,23.4,8.1,20.3,-,15.0,1.2,0.7,0.4
45,2020,영등포구,영등포구,15.8,2.6,0.3,0.2,19.1,19.5,23.5,-,15.8,1.1,1.8,0.2
46,2020,동작구,동작구,11.9,2.1,0.5,1.3,28.3,14.7,22.5,0,15.7,1.8,0.8,0.3
47,2020,관악구,관악구,17.3,1.9,0.4,1.1,24.2,18.0,25.2,0.1,9.5,0.4,0.9,1.1
48,2020,서초구,서초구,19.4,1.5,0.2,0.6,22.7,15.9,15.8,0.2,20.3,2.0,1.2,0.2
49,2020,강남구,강남구,16.1,2.3,0,0.4,16.2,14.2,23.1,0.4,23.5,1.0,2.7,0.2
50,2020,송파구,송파구,17.1,3.3,0.1,0.8,18.4,17.1,16.4,-,23.0,1.0,2.2,0.5
51,2020,강동구,강동구,19.5,3.7,0.2,1.1,23.5,15.5,18.9,0.5,15.2,1.0,0.9,0.2

In [209]:
data3=data3.drop(columns=['기간','대분류'],axis=1)

In [211]:
data3.to_csv('교통수단.csv')

In [212]:
data4=pd.read_excel('./1인가구.xls')
data4

,기간,자치구,성별,합계,주택(거처)의 종류,주택(거처)의 종류.1,주택(거처)의 종류.2,주택(거처)의 종류.3,주택(거처)의 종류.4,주택(거처)의 종류.5,주택이외의 거처
0,기간,자치구,성별,합계,계,단독주택,아파트,연립주택,다세대주택,비거주용 건물내 주택,주택이외의 거처
1,2020,합계,계,1390701,1163690,536654,311112,21613,250810,43501,227011
2,2020,합계,남자,650999,536424,274574,118308,8971,111069,23502,114575
3,2020,합계,여자,739702,627266,262080,192804,12642,139741,19999,112436
4,2020,종로구,계,25983,20750,11208,3691,1009,3993,849,5233
...,...,...,...,...,...,...,...,...,...,...,...
74,2020,송파구,남자,32890,26276,8672,5275,326,10871,1132,6614
75,2020,송파구,여자,40804,33221,8180,9662,494,13981,904,7583
76,2020,강동구,계,50316,43827,19183,11869,381,11003,1391,6489
77,2020,강동구,남자,23817,20442,10120,4576,146,4869,731,3375
78,2020,강동구,여자,26499,23385,9063,7293,235,6134,660,3114

In [213]:
data4=data4.drop(columns=['기간','성별','주택(거처)의 종류','주택(거처)의 종류.1'
                         ,'주택(거처)의 종류.2','주택(거처)의 종류.3',
                         '주택(거처)의 종류.4','주택(거처)의 종류.5',
                         '주택이외의 거처'],axis=1)

In [216]:
data4=data4.groupby('자치구').sum()

In [220]:
data4.to_csv('1인가구.csv')

In [222]:
data5=pd.read_excel('./2019년서울시쓰레기발생.xls')
data5

      기간   컬럼1     발생량     재활용   재활용.1   재활용.2      소각     매립    기타
0     기간   컬럼1     발생량      소계     재활용     음식물      소각     매립    기타
1   2019     계  9847.4  6535.4  3729.3  2806.1  2245.8  978.5  87.7
2   2019  처리비율     100    66.4    37.9    28.5    22.8    9.9   0.9
3   2019   종로구   339.9   219.6   124.5    95.1    79.9   40.3   0.1
4   2019    중구   413.7   224.3   136.5    87.8   133.9   55.5     -
5   2019   용산구   305.2   198.6   127.8    70.8    69.3   31.3     6
6   2019   성동구   303.1   211.4   136.8    74.6    62.6   27.1     2
7   2019   광진구   333.9   253.2   158.7    94.5    59.1   21.2   0.4
8   2019  동대문구   411.2   298.4   205.6    92.8    93.1   19.5   0.2
9   2019   중랑구   330.5   223.1     186    37.1    89.3   17.7   0.4
10  2019   성북구   371.3   275.6   180.5    95.1    86.1    8.8   0.8
11  2019   강북구   251.2   175.3   101.7    73.6      69    6.9     -
12  2019   도봉구   345.1   220.7     140    80.7      76    5.7  42.7
13  2019   노원구   317.3   207.4    82.4     125   104.6    3.9   1.4
14  2019   은평구     369   224.9   150.8    74.1    49.2   94.5   0.4
15  2019  서대문구   240.1   146.5    76.5      70    63.9   29.2   0.5
16  2019   마포구   477.5   285.9   162.5   123.4   147.3   44.1   0.2
17  2019   양천구   340.8   221.5     104   117.5   101.3     18     -
18  2019   강서구   599.4   446.2     286   160.2   115.5   35.7     2
19  2019   구로구   326.5     171    74.1    96.9   124.5   30.9   0.1
20  2019   금천구   286.7     198   135.5    62.5     0.1   88.6     -
21  2019  영등포구   417.3   266.4     111   155.4    99.6   47.6   3.7
22  2019   동작구   315.4   224.9   131.9      93    67.2   23.3     -
23  2019   관악구   434.7   313.2   221.9    91.3    37.7   83.7   0.1
24  2019   서초구   498.3   293.2     114   179.2   129.4   75.4   0.3
25  2019   강남구   591.2   348.2     225   123.2   197.4     44   1.6
26  2019   송파구   808.2   604.8   190.1   414.7   114.9   84.7   3.8
27  2019   강동구   419.9   283.1   165.5   117.6    74.9   40.9    21

In [223]:
data5=data5.drop(columns=['기간','재활용.1','재활용.2'
                         ,'소각','매립','기타'],axis=1)

In [225]:
data5.to_csv('2019년서울시쓰레기.csv')